name: Github Actions With Docker
run-name: ${{ github.actor }} is teesting out GitHub Actions with Docker🚀
on:
  pull_request:
    types:
      - labeled
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "dckr_pat_NzqVfbgbOjFO8E8L1z-Vo6J67Xg" | docker login --username zoubiddounia --password-stdin
      - run: docker build -t zoubiddounia/tp-docker-github:web .
        working-directory: ./web
      - run: docker push zoubiddounia/tp-docker-github:web
      - run: docker build -t zoubiddounia/tp-docker-github:words .
        working-directory: ./words
      - run: docker push zoubiddounia/tp-docker-github:words
      - run: docker build -t zoubiddounia/tp-docker-github:db .
        working-directory: ./db
      - run: docker push zoubiddounia/tp-docker-github:db